version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cafe_order
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - mynetwork
  api:
    container_name: order_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db: